/**
 * @file constraints.c
 * @brief Constraint-file emission for the Verilog-2005 backend.
 */
#include <stdio.h>
#include <string.h>

#include "verilog_backend.h"
#include "verilog_internal.h"
#include "ir.h"
#include "chip_data.h"
#include "util.h"

/* -------------------------------------------------------------------------
 * Xilinx IOSTANDARD name mapping
 *
 * JZ-HDL uses compact names (e.g. TMDS33, LVDS25) but Xilinx XDC requires
 * underscored forms (e.g. TMDS_33, LVDS_25) for certain standards.
 * -------------------------------------------------------------------------
 */
/** Maps JZ-HDL I/O standard spellings to XDC spellings. */
static const struct {
    const char *jz;      /**< Internal JZ-HDL I/O standard name. */
    const char *xilinx;  /**< XDC spelling emitted for the same standard. */
} xdc_std_map[] = {
    { "TMDS33",   "TMDS_33"   },
    { "LVDS25",   "LVDS_25"   },
    { "LVDS33",   "LVDS_33"   },
    { "BLVDS25",  "BLVDS_25"  },
    { "LVPECL33", "LVPECL_33" },
    { NULL, NULL }
};

/**
 * @brief Translate a JZ-HDL I/O standard to the XDC spelling.
 * @param std JZ-HDL I/O standard name.
 * @return Matching XDC spelling, or `std` when no translation is needed.
 */
static const char *xdc_iostandard(const char *std);

static const char *xdc_iostandard(const char *std)
{
    if (!std) return std;
    for (int i = 0; xdc_std_map[i].jz; ++i) {
        if (strcmp(std, xdc_std_map[i].jz) == 0)
            return xdc_std_map[i].xilinx;
    }
    return std;
}

/* -------------------------------------------------------------------------
 * Backend output helpers
 * -------------------------------------------------------------------------
 */

int open_backend_output(const char *target,
                        FILE **out,
                        int *close_out,
                        char *tmp_path,
                        size_t tmp_path_size,
                        JZDiagnosticList *diagnostics,
                        const char *input_filename)
{
    if (!out || !close_out || !tmp_path || tmp_path_size == 0) {
        return -1;
    }
    *out = NULL;
    *close_out = 0;
    tmp_path[0] = '\0';

    if (!target || target[0] == '\0' || strcmp(target, "-") == 0) {
        *out = stdout;
        *close_out = 0;
        return 0;
    }

    if (jz_open_exclusive_temp_output(target, out, tmp_path, tmp_path_size) != 0) {
        backend_io_error(diagnostics, input_filename,
                         "failed to open temporary constraint output file for writing");
        return -1;
    }
    *close_out = 1;
    return 0;
}

int close_backend_output(FILE *out,
                         int close_out,
                         const char *tmp_path,
                         const char *final_path,
                         JZDiagnosticList *diagnostics,
                         const char *input_filename)
{
    if (!close_out) {
        return 0;
    }

    if (!out || !tmp_path || !final_path || final_path[0] == '\0') {
        return -1;
    }

    if (jz_commit_exclusive_temp_output(out, tmp_path, final_path) != 0) {
        backend_io_error(diagnostics, input_filename,
                         "failed to finalize constraint output");
        return -1;
    }
    return 0;
}

/* -------------------------------------------------------------------------
 * SDC constraint emission
 * -------------------------------------------------------------------------
 */

int jz_emit_sdc_constraints(const IR_Design *design,
                            const char *filename,
                            JZDiagnosticList *diagnostics,
                            const char *input_filename)
{
    if (!design || !design->project) {
        return 0;
    }

    const IR_Project *proj = design->project;
    const char *target = (filename && filename[0] != '\0') ? filename : "-";

    FILE *out = NULL;
    int close_out = 0;
    char tmp_path[1024];

    if (open_backend_output(target, &out, &close_out,
                            tmp_path, sizeof(tmp_path),
                            diagnostics, input_filename) != 0) {
        return -1;
    }

    fprintf(out, "# SDC constraints generated by jz-hdl for project '");
    verilog_emit_constraint_comment_text(out, proj->name ? proj->name : "project");
    fprintf(out, "'\n");

    for (int i = 0; i < proj->num_clocks; ++i) {
        const IR_Clock *clk = &proj->clocks[i];
        if (!clk->name || clk->name[0] == '\0') {
            continue;
        }
        if (clk->period_ns <= 0.0) {
            continue;
        }
        if (!verilog_constraint_value_is_safe(clk->name)) {
            backend_io_error(diagnostics, input_filename,
                             "refusing to emit unsafe clock name into SDC output");
            if (close_out) fclose(out);
            return -1;
        }
        const char *target_cmd = clk->is_generated ? "get_nets" : "get_ports";

        /* For differential clock pins, the Verilog port is <name>_p, not <name>.
         * Check if this clock name matches a differential pin. */
        int clk_is_diff = 0;
        if (!clk->is_generated) {
            for (int m = 0; m < proj->num_mappings; ++m) {
                const IR_PinMapping *mp = &proj->mappings[m];
                if (mp->logical_pin_name && clk->name &&
                    strcmp(mp->logical_pin_name, clk->name) == 0 &&
                    mp->board_pin_n_id && mp->board_pin_n_id[0] != '\0') {
                    clk_is_diff = 1;
                    break;
                }
            }
        }

        if (clk_is_diff) {
            fprintf(out, "create_clock -name ");
            verilog_emit_tcl_braced(out, clk->name);
            fprintf(out, " -period %g [%s ", clk->period_ns, target_cmd);
            {
                char port_name[512];
                snprintf(port_name, sizeof(port_name), "%s_p", clk->name);
                verilog_emit_tcl_braced(out, port_name);
            }
            fprintf(out, "]\n");
        } else {
            fprintf(out, "create_clock -name ");
            verilog_emit_tcl_braced(out, clk->name);
            fprintf(out, " -period %g [%s ", clk->period_ns, target_cmd);
            verilog_emit_tcl_braced(out, clk->name);
            fprintf(out, "]\n");
        }
    }

    if (close_backend_output(out, close_out,
                             tmp_path, target,
                             diagnostics, input_filename) != 0) {
        return -1;
    }
    return 0;
}

/* -------------------------------------------------------------------------
 * XDC constraint emission
 * -------------------------------------------------------------------------
 */

int jz_emit_xdc_constraints(const IR_Design *design,
                            const char *filename,
                            JZDiagnosticList *diagnostics,
                            const char *input_filename)
{
    if (!design || !design->project) {
        return 0;
    }

    const IR_Project *proj = design->project;
    const char *target = (filename && filename[0] != '\0') ? filename : "-";

    FILE *out = NULL;
    int close_out = 0;
    char tmp_path[1024];

    if (open_backend_output(target, &out, &close_out,
                            tmp_path, sizeof(tmp_path),
                            diagnostics, input_filename) != 0) {
        return -1;
    }

    fprintf(out, "# XDC pin constraints generated by jz-hdl for project '");
    verilog_emit_constraint_comment_text(out, proj->name ? proj->name : "project");
    fprintf(out, "'\n");

    for (int i = 0; i < proj->num_mappings; ++i) {
        const IR_PinMapping *m = &proj->mappings[i];
        if (!m->logical_pin_name || !m->board_pin_id) {
            continue;
        }

        const IR_Pin *pin = NULL;
        for (int p = 0; p < proj->num_pins; ++p) {
            const IR_Pin *candidate = &proj->pins[p];
            if (candidate->name &&
                strcmp(candidate->name, m->logical_pin_name) == 0) {
                pin = candidate;
                break;
            }
        }
        if (!pin) {
            continue;
        }

        const char *port_name = pin->name ? pin->name : "jz_pin";
        int is_diff = (m->board_pin_n_id && m->board_pin_n_id[0] != '\0');
        if (!verilog_constraint_value_is_safe(port_name) ||
            !verilog_constraint_value_is_safe(m->board_pin_id) ||
            (m->board_pin_n_id && m->board_pin_n_id[0] != '\0' &&
             !verilog_constraint_value_is_safe(m->board_pin_n_id)) ||
            (pin->standard && pin->standard[0] != '\0' &&
             !verilog_constraint_value_is_safe(xdc_iostandard(pin->standard)))) {
            backend_io_error(diagnostics, input_filename,
                             "refusing to emit unsafe pin metadata into XDC output");
            if (close_out) fclose(out);
            return -1;
        }

        if (is_diff) {
            /* Differential pins: Verilog backend emits ports with _p/_n suffixes.
             * Array pins are flattened: CLK0_p (not CLK_p[0]).
             * Emit separate constraints for both P and N ports. */
            char p_port[256], n_port[256];
            if (m->bit_index >= 0) {
                snprintf(p_port, sizeof(p_port), "%s%d_p", port_name, m->bit_index);
                snprintf(n_port, sizeof(n_port), "%s%d_n", port_name, m->bit_index);
            } else {
                snprintf(p_port, sizeof(p_port), "%s_p", port_name);
                snprintf(n_port, sizeof(n_port), "%s_n", port_name);
            }

            /* P pin constraints */
            fprintf(out, "set_property PACKAGE_PIN %s", m->board_pin_id);
            fprintf(out, " [get_ports ");
            verilog_emit_tcl_braced(out, p_port);
            fprintf(out, "]\n");
            fprintf(out, "set_property LOC %s", m->board_pin_id);
            fprintf(out, " [get_ports ");
            verilog_emit_tcl_braced(out, p_port);
            fprintf(out, "]\n");
            if (pin->standard && pin->standard[0] != '\0') {
                fprintf(out, "set_property IOSTANDARD ");
                verilog_emit_tcl_braced(out, xdc_iostandard(pin->standard));
                fprintf(out, " [get_ports ");
                verilog_emit_tcl_braced(out, p_port);
                fprintf(out, "]\n");
            }

            /* Differential termination */
            if (pin->kind == PIN_IN || pin->kind == PIN_INOUT) {
                if (pin->term) {
                    fprintf(out, "set_property DIFF_TERM TRUE [get_ports ");
                    verilog_emit_tcl_braced(out, p_port);
                    fprintf(out, "]\n");
                } else {
                    fprintf(out, "set_property DIFF_TERM FALSE [get_ports ");
                    verilog_emit_tcl_braced(out, p_port);
                    fprintf(out, "]\n");
                }
            }

            /* SLEW FAST for differential output pins with serializers */
            if (pin->kind == PIN_OUT && pin->fclk_name && pin->fclk_name[0]) {
                fprintf(out, "set_property SLEW FAST [get_ports ");
                verilog_emit_tcl_braced(out, p_port);
                fprintf(out, "]\n");
            }

            /* N pin constraints */
            fprintf(out, "set_property PACKAGE_PIN %s", m->board_pin_n_id);
            fprintf(out, " [get_ports ");
            verilog_emit_tcl_braced(out, n_port);
            fprintf(out, "]\n");
            fprintf(out, "set_property LOC %s", m->board_pin_n_id);
            fprintf(out, " [get_ports ");
            verilog_emit_tcl_braced(out, n_port);
            fprintf(out, "]\n");
            if (pin->standard && pin->standard[0] != '\0') {
                fprintf(out, "set_property IOSTANDARD ");
                verilog_emit_tcl_braced(out, xdc_iostandard(pin->standard));
                fprintf(out, " [get_ports ");
                verilog_emit_tcl_braced(out, n_port);
                fprintf(out, "]\n");
            }

            /* SLEW FAST on N pin too (prjxray configures each IOB independently) */
            if (pin->kind == PIN_OUT && pin->fclk_name && pin->fclk_name[0]) {
                fprintf(out, "set_property SLEW FAST [get_ports ");
                verilog_emit_tcl_braced(out, n_port);
                fprintf(out, "]\n");
            }
        } else {
            /* Single-ended pin */
            fprintf(out, "set_property PACKAGE_PIN %s", m->board_pin_id);
            fprintf(out, " [get_ports ");
            fputc('{', out);
            fprintf(out, "%s", port_name);
            if (m->bit_index >= 0) {
                fprintf(out, "[%d]", m->bit_index);
            }
            fprintf(out, "}]\n");
            fprintf(out, "set_property LOC %s", m->board_pin_id);
            fprintf(out, " [get_ports ");
            fputc('{', out);
            fprintf(out, "%s", port_name);
            if (m->bit_index >= 0) {
                fprintf(out, "[%d]", m->bit_index);
            }
            fprintf(out, "}]\n");

            if (pin->standard && pin->standard[0] != '\0') {
                fprintf(out, "set_property IOSTANDARD ");
                verilog_emit_tcl_braced(out, xdc_iostandard(pin->standard));
                fprintf(out, " [get_ports ");
                fputc('{', out);
                fprintf(out, "%s", port_name);
                if (m->bit_index >= 0) {
                    fprintf(out, "[%d]", m->bit_index);
                }
                fprintf(out, "}]\n");
            }
            if (pin->drive_ma >= 0) {
                fprintf(out, "set_property DRIVE %d [get_ports {%s",
                        pin->drive_ma, port_name);
                if (m->bit_index >= 0) {
                    fprintf(out, "[%d]", m->bit_index);
                }
                fprintf(out, "}]\n");
            }
            if (pin->pull == PULL_UP) {
                fprintf(out, "set_property PULLTYPE PULLUP [get_ports {%s",
                        port_name);
                if (m->bit_index >= 0) {
                    fprintf(out, "[%d]", m->bit_index);
                }
                fprintf(out, "}]\n");
            } else if (pin->pull == PULL_DOWN) {
                fprintf(out, "set_property PULLTYPE PULLDOWN [get_ports {%s",
                        port_name);
                if (m->bit_index >= 0) {
                    fprintf(out, "[%d]", m->bit_index);
                }
                fprintf(out, "}]\n");
            }

            /* Input termination: always emit IN_TERM for input pins */
            if (pin->kind == PIN_IN || pin->kind == PIN_INOUT) {
                const char *in_term = pin->term ? "UNTUNED_SPLIT_50" : "NONE";
                fprintf(out, "set_property IN_TERM %s [get_ports {%s",
                        in_term, port_name);
                if (m->bit_index >= 0) {
                    fprintf(out, "[%d]", m->bit_index);
                }
                fprintf(out, "}]\n");
            }
        }
    }

    if (close_backend_output(out, close_out,
                             tmp_path, target,
                             diagnostics, input_filename) != 0) {
        return -1;
    }
    return 0;
}

/* -------------------------------------------------------------------------
 * PCF constraint emission
 * -------------------------------------------------------------------------
 */

int jz_emit_pcf_constraints(const IR_Design *design,
                            const char *filename,
                            JZDiagnosticList *diagnostics,
                            const char *input_filename)
{
    if (!design || !design->project) {
        return 0;
    }

    const IR_Project *proj = design->project;
    const char *target = (filename && filename[0] != '\0') ? filename : "-";

    FILE *out = NULL;
    int close_out = 0;
    char tmp_path[1024];

    if (open_backend_output(target, &out, &close_out,
                            tmp_path, sizeof(tmp_path),
                            diagnostics, input_filename) != 0) {
        return -1;
    }

    fprintf(out, "# PCF pin constraints generated by jz-hdl for project '");
    verilog_emit_constraint_comment_text(out, proj->name ? proj->name : "project");
    fprintf(out, "'\n");

    for (int i = 0; i < proj->num_mappings; ++i) {
        const IR_PinMapping *m = &proj->mappings[i];
        if (!m->logical_pin_name || !m->board_pin_id) {
            continue;
        }
        if (!verilog_constraint_value_is_safe(m->logical_pin_name) ||
            !verilog_constraint_value_is_safe(m->board_pin_id) ||
            (m->board_pin_n_id && m->board_pin_n_id[0] != '\0' &&
             !verilog_constraint_value_is_safe(m->board_pin_n_id))) {
            backend_io_error(diagnostics, input_filename,
                             "refusing to emit unsafe pin metadata into PCF output");
            if (close_out) fclose(out);
            return -1;
        }
        int is_diff = (m->board_pin_n_id && m->board_pin_n_id[0] != '\0');
        if (is_diff) {
            /* Differential pins: emit separate P/N entries matching
             * the Verilog port names (<name><bit>_p, <name><bit>_n). */
            if (m->bit_index >= 0) {
                fprintf(out, "set_io %s%d_p %s\n",
                        m->logical_pin_name, m->bit_index, m->board_pin_id);
                fprintf(out, "set_io %s%d_n %s\n",
                        m->logical_pin_name, m->bit_index, m->board_pin_n_id);
            } else {
                fprintf(out, "set_io %s_p %s\n",
                        m->logical_pin_name, m->board_pin_id);
                fprintf(out, "set_io %s_n %s\n",
                        m->logical_pin_name, m->board_pin_n_id);
            }
        } else {
            fprintf(out, "set_io %s", m->logical_pin_name);
            if (m->bit_index >= 0) {
                fprintf(out, "[%d]", m->bit_index);
            }
            fprintf(out, " %s\n", m->board_pin_id);
        }
    }

    if (close_backend_output(out, close_out,
                             tmp_path, target,
                             diagnostics, input_filename) != 0) {
        return -1;
    }
    return 0;
}

/* -------------------------------------------------------------------------
 * CST constraint emission (Gowin)
 * -------------------------------------------------------------------------
 */

int jz_emit_cst_constraints(const IR_Design *design,
                            const char *filename,
                            JZDiagnosticList *diagnostics,
                            const char *input_filename)
{
    if (!design || !design->project) {
        return 0;
    }

    const IR_Project *proj = design->project;
    const char *target = (filename && filename[0] != '\0') ? filename : "-";

    FILE *out = NULL;
    int close_out = 0;
    char tmp_path[1024];

    if (open_backend_output(target, &out, &close_out,
                            tmp_path, sizeof(tmp_path),
                            diagnostics, input_filename) != 0) {
        return -1;
    }

    /* Load chip data for differential IO_TYPE override */
    JZChipData cst_chip_data;
    int have_chip_data = 0;
    const char *diff_io_type = NULL;
    if (proj->chip_id && proj->chip_id[0]) {
        JZChipLoadStatus st = jz_chip_data_load(proj->chip_id, input_filename, &cst_chip_data);
        if (st == JZ_CHIP_LOAD_OK) {
            have_chip_data = 1;
            diff_io_type = jz_chip_diff_io_type(&cst_chip_data);
        }
    }

    fprintf(out, "// CST pin constraints generated by jz-hdl for project '");
    verilog_emit_constraint_comment_text(out, proj->name ? proj->name : "project");
    fprintf(out, "'\n");

    for (int i = 0; i < proj->num_mappings; ++i) {
        const IR_PinMapping *m = &proj->mappings[i];
        if (!m->logical_pin_name || !m->board_pin_id) {
            continue;
        }

        const IR_Pin *pin = NULL;
        for (int p = 0; p < proj->num_pins; ++p) {
            const IR_Pin *candidate = &proj->pins[p];
            if (candidate->name &&
                strcmp(candidate->name, m->logical_pin_name) == 0) {
                pin = candidate;
                break;
            }
        }

        int is_diff = (m->board_pin_n_id && m->board_pin_n_id[0] != '\0');
        if (!verilog_constraint_value_is_safe(m->logical_pin_name) ||
            !verilog_constraint_value_is_safe(m->board_pin_id) ||
            (m->board_pin_n_id && m->board_pin_n_id[0] != '\0' &&
             !verilog_constraint_value_is_safe(m->board_pin_n_id)) ||
            (pin && pin->standard && pin->standard[0] != '\0' &&
             !verilog_constraint_value_is_safe(pin->standard)) ||
            (diff_io_type && !verilog_constraint_value_is_safe(diff_io_type))) {
            backend_io_error(diagnostics, input_filename,
                             "refusing to emit unsafe pin metadata into CST output");
            if (have_chip_data) {
                jz_chip_data_free(&cst_chip_data);
            }
            if (close_out) fclose(out);
            return -1;
        }

        if (is_diff) {
            /* Differential pins: combined IO_LOC "name_p" P,N; format.
             * nextpnr CST parser auto-pairs _p → _n for the complementary port.
             * Uses lowercase _p/_n to match nextpnr's regex (_p$ → _n).
             * Array pins are flattened: TMDS_DATA0_p (not TMDS_DATA_p[0])
             * so _p is always at the end of the name. */
            if (m->bit_index >= 0) {
                fprintf(out, "IO_LOC \"%s%d_p\" %s,%s;\n",
                        m->logical_pin_name, m->bit_index,
                        m->board_pin_id, m->board_pin_n_id);
            } else {
                fprintf(out, "IO_LOC \"%s_p\" %s,%s;\n",
                        m->logical_pin_name,
                        m->board_pin_id, m->board_pin_n_id);
            }

            /* IO_PORT for differential _p pin */
            if (pin && pin->standard && pin->standard[0] != '\0') {
                if (m->bit_index >= 0) {
                    fprintf(out, "IO_PORT \"%s%d_p\"", m->logical_pin_name, m->bit_index);
                } else {
                    fprintf(out, "IO_PORT \"%s_p\"", m->logical_pin_name);
                }
                /* Use chip-specific IO_TYPE for differential pins when available
                 * (e.g., LVCMOS33D for emulated LVDS on GW1NR-9). */
                const char *io_type = diff_io_type ? diff_io_type : pin->standard;
                fprintf(out, " IO_TYPE=%s PULL_MODE=NONE", io_type);
                if (pin->drive > 0.0) {
                    if (pin->drive == (double)(int)pin->drive) {
                        fprintf(out, " DRIVE=%d", (int)pin->drive);
                    } else {
                        fprintf(out, " DRIVE=%.1f", pin->drive);
                    }
                } else if (pin->drive_ma >= 0) {
                    fprintf(out, " DRIVE=%d", pin->drive_ma);
                }
                if (pin->term) {
                    fprintf(out, " TERM=100");
                }
                fprintf(out, ";\n");
            }
        } else {
            /* Single-ended pin */
            fprintf(out, "IO_LOC \"%s", m->logical_pin_name);
            if (m->bit_index >= 0) {
                fprintf(out, "[%d]", m->bit_index);
            }
            fprintf(out, "\" %s;\n", m->board_pin_id);

            /* IO_PORT with attributes */
            if (pin && pin->standard && pin->standard[0] != '\0') {
                fprintf(out, "IO_PORT \"%s", m->logical_pin_name);
                if (m->bit_index >= 0) {
                    fprintf(out, "[%d]", m->bit_index);
                }
                fprintf(out, "\" IO_TYPE=%s", pin->standard);

                /* Pull mode */
                if (pin->pull == PULL_UP) {
                    fprintf(out, " PULL_MODE=UP");
                } else if (pin->pull == PULL_DOWN) {
                    fprintf(out, " PULL_MODE=DOWN");
                }

                /* Termination */
                if (pin->term) {
                    fprintf(out, " TERM=100");
                }

                fprintf(out, ";\n");
            }
        }
    }

    if (have_chip_data) {
        jz_chip_data_free(&cst_chip_data);
    }

    if (close_backend_output(out, close_out,
                             tmp_path, target,
                             diagnostics, input_filename) != 0) {
        return -1;
    }
    return 0;
}
