# XDC pin constraints generated by jz-hdl for project 'CONSTRAINT_OUTPUT_ESCAPING'
set_property PACKAGE_PIN 4 [get_ports {SCLK}]
set_property LOC 4 [get_ports {SCLK}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SCLK}]
set_property IN_TERM NONE [get_ports {SCLK}]
set_property PACKAGE_PIN 15 [get_ports {LED}]
set_property LOC 15 [get_ports {LED}]
set_property IOSTANDARD {LVCMOS33} [get_ports {LED}]
set_property DRIVE 8 [get_ports {LED}]
